# docker-compose.yml
version: '3'

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user1
      DB_PASSWORD: 123456Aa
      DB_NAME: pbl4-db

