version: '3.7'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: pbl4-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456Aa
      MYSQL_DATABASE: pbl4-db
    ports:
      - "3308:3306"  
    volumes:
    # Mysql
    - db:/var/lib/mysql
    networks: 
      - nodejss

  web:
    depends_on:
      - mysql
    build: ./myapp
    ports: 
      - "3011:3011"
    volumes:
    - ./myapp/:/app
    restart: unless-stopped
    container_name: nodejs
    stdin_open: true
    tty: true
    networks: 
      - nodejss

volumes:
  db:

networks:
  nodejss:
